kind: Service
apiVersion: v1
metadata:
  name: coffee-shop
  labels:
    app: coffee-shop
spec:
  selector:
    app: coffee-shop
  ports:
    - port: 9080
      name: http
---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: coffee-shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: coffee-shop
        version: v1
    spec:
      containers:
      - name: coffee-shop
        image: sdaschner/coffee-shop:12factor-1
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - curl -f localhost:9080/
          initialDelaySeconds: 40
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - curl -f localhost:9080/coffee-shop/resources/health
          initialDelaySeconds: 60
        env:
        - name: DEVELOPMENT
          valueFrom:
            configMapKeyRef:
              name: coffee-shop-config
              key: developmentMode
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: coffee-shop-config
data:
  developmentMode: "true"
---

