apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: coffee-shop-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: coffee-shop
spec:
  hosts:
  - "*"
  gateways:
  - coffee-shop-gateway
  http:
  - route:
    - destination:
        host: coffee-shop
        port:
          number: 9080
        subset: v1
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: coffee-shop
spec:
  host: coffee-shop
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 4
      http:
        http1MaxPendingRequests: 4
        maxRequestsPerConnection: 2
  subsets:
  - name: v1
    labels:
      version: v1
---

# to self
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: coffee-shop
spec:
  hosts:
  - "coffee-shop.example.com"
  addresses:
  - "169.46.11.42"
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: NONE
  location: MESH_EXTERNAL
---
